CREATE DATABASE IF NOT EXISTS 'kong-db';
CREATE DATABASE IF NOT EXISTS 'auth-db';
CREATE DATABASE IF NOT EXISTS 'order-db';
CREATE DATABASE IF NOT EXISTS 'inventory-db';
CREATE DATABASE IF NOT EXISTS 'payment-db';